### ISSUE TITLE
Negative Containment check possible?

### ISSUE THREAD

**Issue by slowpokefarm** [nicoSWD/php-rule-parser#14]
Is it possible to do a negative containment check, like `!in_array(needle, haystack)` ?
I have tried `x not in y` and `x !in y` and both failed.

**Comment by nicoSWD** [comment]
Hey @slowpokefarm 

there's currently no support for that. You could implement a custom function if you're using the Symfony bundle

https://github.com/nicoSWD/rule-engine-bundle#custom-functions

Although I might add support for `!` is a future release.

Thanks!

**Comment by nicoSWD** [comment]
Hey @slowpokefarm!

Native support for `not in` has been added in [0.6.1](https://github.com/nicoSWD/php-rule-parser/releases/tag/0.6.1)
