### ISSUE TITLE
Being worked on?

### ISSUE THREAD

**Issue by jhgeluk** [nicoSWD/php-rule-parser#23]
Will there be any future updates/changes to this library?

**Comment by nicoSWD** [comment]
Hey @jhgeluk 

no big changes are planned for the near future, but it's still maintained. Anything you're missing or waiting for?

**Comment by jhgeluk** [comment]
It would be a nice addition to see the following features (as described on the todo list):
- Support for object properties (foo.length)
- Support for returning actual results, other than true or false
- Support for array / string dereferencing: "foo"[1]

**Comment by jhgeluk** [comment]
Also it's quite hard to transform multidimensional/deeply nested arrays to a condition string to be used in the rule engine

**Comment by nicoSWD** [comment]
@jhgeluk not sure if you still care, but the latest release addresses some of these issues!
