### ISSUE TITLE
ReadMe Mis-type?

### ISSUE THREAD

**Issue by frankieeedeee** [nicoSWD/php-rule-parser#7]
Hi There,

Just getting to know this package and had a tough time getting up and running with it, PHP throwing exceptions about now being able to find the class itself. Mucked around with composer to no avail, then took a look under the hood and saw that the namespace of this library should be `nicoSWD\Rules\....` note the Rule**s** plural, however it's got in the example Read Me, `use nicoSWD\Rule\Rule` - Might just want to double check the docs!

Cheers :)

**Comment by nicoSWD** [comment]
Hey @frankieeedeee!

Thanks for bringing this up. Is there a chance you're using an older version of this library? Version 0.4 and below used `Rules` as part of the namespace, but it was later changed to `Rule`.

Here's a compatible readme:
https://github.com/nicoSWD/php-rule-parser/blob/0.4.0/README.md

Let me know if that's it or if I'm missing something!

Thank you! 🙂
